// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace WebApi.Migrations
{
    [DbContext(typeof(GestionPersonaContext))]
    partial class GestionPersonaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("Models.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pais");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Argentina"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Chile"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Uruguay"
                        });
                });

            modelBuilder.Entity("Models.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nacionalidad")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("NroDocumento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PaisId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SexoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PaisId");

                    b.HasIndex("SexoId");

                    b.ToTable("Persona");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Pintos",
                            Email = "micorreo@gmail.com",
                            FechaNacimiento = new DateTime(2020, 7, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Marcos",
                            NroDocumento = "12345678",
                            PaisId = 1,
                            SexoId = 1,
                            Telefono = "1111",
                            TipoDocumento = "dni"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "Lopez",
                            Email = "lucas@gmail.com",
                            FechaNacimiento = new DateTime(2020, 7, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Maria",
                            NroDocumento = "12345679",
                            PaisId = 2,
                            SexoId = 2,
                            Telefono = "2222",
                            TipoDocumento = "dni"
                        });
                });

            modelBuilder.Entity("Models.Sexo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sexo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Hombre"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Mujer"
                        });
                });

            modelBuilder.Entity("Models.Persona", b =>
                {
                    b.HasOne("Models.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Sexo", "Sexo")
                        .WithMany()
                        .HasForeignKey("SexoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
